/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.74.0
  Forc version: 0.50.0
  Fuel-Core version: 0.22.1
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export enum ContractBErrorInput { AlreadyInitialized = 'AlreadyInitialized' };
export enum ContractBErrorOutput { AlreadyInitialized = 'AlreadyInitialized' };

interface ContractBAbiInterface extends Interface {
  functions: {
    method: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'method', values: []): Uint8Array;

  decodeFunctionData(functionFragment: 'method', data: BytesLike): DecodedValue;
}

export class ContractBAbi extends Contract {
  interface: ContractBAbiInterface;
  functions: {
    method: InvokeFunction<[], void>;
  };
}
