/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.74.0
  Forc version: 0.50.0
  Fuel-Core version: 0.22.1
*/

export type { ContractAAbi } from './ContractAAbi';
export type { ContractBAbi } from './ContractBAbi';

export { ContractAAbi__factory } from './factories/ContractAAbi__factory';
export { ContractBAbi__factory } from './factories/ContractBAbi__factory';
